language: "javascript"
nodejs:
  - 6.9.1
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
    - 104.248.169.34 # your droplet IP goes here
branches:
  only:
    - master
env:
  global:
    - REMOTEAPPDIR=/var/www/marcelchristie.com/
    - REMOTEUSER=deploy
    - REMOTEHOST=104.248.169.34 # your droplet IP goes here
    - PORT=8080
beforeinstall:
  - npm install -g npm@^2
install:
  - npm install --only=dev
beforescript:
  - chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
  - npm run build
after_success:
  - "./scripts/deploy.sh"