sudo: required
services:
  - docker

before_install:
  - docker build -t marcel13/docker-ang -f Dockerfile.dev .

script:
  - docker run -e CI=true marcel13/docker-ang npm run test


deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react-test'
  env: 'Dockerreacttest-env'
  bucket: 'elasticbeanstalk-us-east-2-389498829844'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
